### ISSUE TITLE
tests don't run on Mac OS: parasailors build

### ISSUE THREAD

**Issue by pmarks** [aseyboldt/fastq-rs#9]
The build of parasailors fails inside it's build.rs.  I'd recommend dropping parasailors as a dev dependency because it's not critical for testing `fastq` or demonstrating it's functionality, and projects with native code are less likely to build successfully than pure-Rust crates.

```
error: failed to run custom build command for `parasail-sys v0.2.5`

Caused by:
  process didn't exit successfully: `/Users/patrick/code/fastq-rs/target/debug/build/parasail-sys-7eb8e8d2fd2591d9/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Problem copying library to target directoy.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
stack backtrace:
   0:        0x1009c4b62 - backtrace::backtrace::libunwind::trace::hce12a9913e4eeca6
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:        0x1009c4b62 - backtrace::backtrace::trace_unsynchronized::h56a939a6ba5a4791
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:        0x1009c4b62 - std::sys_common::backtrace::_print::h587c601f87837d17
                               at src/libstd/sys_common/backtrace.rs:47
   3:        0x1009c4b62 - std::sys_common::backtrace::print::hded6a7e1e62f7308
                               at src/libstd/sys_common/backtrace.rs:36
   4:        0x1009c4b62 - std::panicking::default_hook::{{closure}}::h3f994bbc901f9889
                               at src/libstd/panicking.rs:200
   5:        0x1009c482d - std::panicking::default_hook::h6c261b7dad1af707
                               at src/libstd/panicking.rs:214
   6:        0x1009c5280 - std::panicking::rust_panic_with_hook::hd3c20890ac648923
                               at src/libstd/panicking.rs:477
   7:        0x1009c4dbd - std::panicking::continue_panic_fmt::hf444d349a369432b
```

**Comment by sstadick** [comment]
@pmarks, have you heard anything back regarding your requested changes? I've got a PR for adding Fasta support, but I'm wondering if it's worth waiting on that since it seems like @aseyboldt hasn't touched this since 2018. I may just make my fork it's own renamed lib.

Oddly though, parasailor tests ran fine for me on mac.
